# Generated by Django 4.2.5 on 2023-11-09 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee", "0003_alter_employeeeducationdetail_percentagepg"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company1name", models.CharField(max_length=100, null=True)),
                ("company1designation", models.CharField(max_length=100, null=True)),
                ("company1salary", models.IntegerField(null=True)),
                (
                    "company1duration",
                    models.DecimalField(decimal_places=1, max_digits=2, null=True),
                ),
                ("company2name", models.CharField(max_length=100, null=True)),
                ("company2designation", models.CharField(max_length=100, null=True)),
                ("company2salary", models.IntegerField(null=True)),
                (
                    "company2duration",
                    models.DecimalField(decimal_places=1, max_digits=2, null=True),
                ),
                ("company3name", models.CharField(max_length=100, null=True)),
                ("company3designation", models.CharField(max_length=100, null=True)),
                ("company3salary", models.IntegerField(null=True)),
                (
                    "company3duration",
                    models.DecimalField(decimal_places=1, max_digits=2, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
