# Generated by Django 4.2.5 on 2023-11-09 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_employeeeducationdetail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeEducationDetail",
        ),
    ]
